# Generated by Django 5.2.8 on 2026-02-22 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category_pattern_approach_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unstructured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='user.unstructured')),
            ],
        ),
    ]
