# Generated by Django 5.2.8 on 2026-09-08 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0003_unstructured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=128)),
                ('middle_name', models.CharField(blank=True, default='', max_length=128)),
                ('last_name', models.CharField(default='', max_length=128)),
                ('designation', models.CharField(blank=True, help_text="Target role (e.g. 'Senior Backend Engineer')", max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=32)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('master_resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('summary', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('current_location', models.CharField(blank=True, max_length=128)),
                ('preferred_locations', models.JSONField(default=list, help_text="e.g. ['Bangalore', 'Remote']")),
                ('last_job_location', models.CharField(blank=True, max_length=128)),
                ('willingness_to_relocate', models.BooleanField(default=False)),
                ('current_salary_fixed', models.PositiveIntegerField(default=0, help_text='Absolute fixed value (e.g. 1200000)')),
                ('current_salary_variable', models.PositiveIntegerField(default=0, help_text='Absolute variable value (e.g. 300000)')),
                ('expected_salary', models.PositiveIntegerField(default=0, help_text='Absolute total expected value (e.g. 2000000)')),
                ('currency', models.CharField(default='INR', help_text="e.g. 'INR', 'USD'", max_length=3)),
                ('notice_period_days', models.IntegerField(default=30)),
                ('work_authorization', models.CharField(blank=True, help_text="e.g. 'Citizen', 'Visa Required'", max_length=128)),
                ('core_skills', models.JSONField(default=list, help_text="e.g. ['Python', 'Django', 'AWS']")),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text="e.g. 'What is your gender?'", max_length=255)),
                ('category', models.CharField(choices=[('DEMOGRAPHIC', 'Demographic (Race, Gender, Veteran)'), ('SENSITIVE', 'Sensitive (Salary, Sponsorship)'), ('GENERAL', 'General (Notice period, Why us?)')], default='GENERAL', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='BulletPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Dealbreaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(help_text="e.g. 'Security Clearance', 'US Citizen Only'", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealbreakers', to='user.applicantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=128)),
                ('degree', models.CharField(max_length=128)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='user.applicantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('tech_stacks', models.JSONField(default=list, help_text="e.g. ['Unity', 'C#']")),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='user.applicantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='user.applicantprofile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='user.question')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128)),
                ('job_title', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('tech_stacks', models.JSONField(default=list, help_text="e.g. ['Python', 'AWS']")),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='user.applicantprofile')),
            ],
        ),
    ]
