# Generated by Django 5.2.8 on 2025-11-19 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=64)),
                ('recruiter', models.CharField(max_length=64)),
                ('contact', models.CharField(max_length=16)),
                ('agency', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(max_length=64)),
                ('apply_url', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('NA', 'Not Applied'), ('AF', 'Applied'), ('CR', 'Call Received'), ('IS', 'Interview Scheduled'), ('RP', 'Response Pending'), ('NE', 'Negotiating'), ('RE', 'Rejected'), ('OR', 'Offer Received')], default='NA', max_length=16)),
                ('last_interaction', models.DateField()),
                ('applied_on', models.DateField()),
                ('last_posted', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=64)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
    ]
