# Generated by Django 5.2.8 on 2025-11-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('LI', 'linkedIn'), ('NI', 'naukri')], max_length=16)),
                ('data', models.TextField()),
            ],
        ),
    ]
