# Generated by Django 5.2.8 on 2025-11-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('scanned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
