# Generated by Django 5.2.8 on 2025-11-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_joburl'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=64)),
                ('job_title', models.CharField(max_length=64)),
                ('job_info', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='joburl',
            name='created_at',
        ),
    ]
