# Generated by Django 5.2.8 on 2025-11-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobraw_remove_joburl_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobraw',
            name='job_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='jobraw',
            name='job_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
