# Generated by Django 5.2.8 on 2025-11-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_jobraw_job_id_jobraw_job_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobraw',
            name='job_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='jobraw',
            name='job_url',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='session',
            name='platform',
            field=models.CharField(choices=[('LI', 'linkedIn'), ('NI', 'naukri'), ('RAW', 'raw_data')], max_length=16),
        ),
    ]
