# Generated by Django 5.2.8 on 2025-11-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_jobraw_job_id_alter_jobraw_job_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='experience_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='experience_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tech_stack_all',
            field=models.CharField(default='[]', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='tech_stack_primary',
            field=models.CharField(default='[]', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='agency',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='contact',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='recruiter',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('IG', 'Ignored'), ('NA', 'Not Applied'), ('AF', 'Applied'), ('CR', 'Call Received'), ('IS', 'Interview Scheduled'), ('RP', 'Response Pending'), ('NE', 'Negotiating'), ('RE', 'Rejected'), ('OR', 'Offer Received')], default='NA', max_length=16),
        ),
        migrations.AlterField(
            model_name='jobraw',
            name='job_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
