# Generated by Django 5.2.8 on 2025-11-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_techstack_job_experience_max_job_experience_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobraw',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
    ]
