# Generated by Django 5.2.8 on 2025-11-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_jobraw_parsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applied_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_interaction',
            field=models.DateField(null=True),
        ),
    ]
