# Generated by Django 5.2.8 on 2025-11-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_job_applied_on_alter_job_last_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_min',
            field=models.IntegerField(null=True),
        ),
    ]
