# Generated by Django 5.2.8 on 2025-12-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_alter_job_experience_max_alter_job_experience_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
