# Generated by Django 5.2.8 on 2025-12-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_posting_ignore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
