# Generated by Django 5.2.8 on 2025-12-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_alter_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobraw',
            name='job_id',
            field=models.CharField(max_length=64),
        ),
    ]
