# Generated by Django 5.2.8 on 2025-12-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_jobraw_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_interaction',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
