# Generated by Django 5.2.8 on 2026-02-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_alter_job_last_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='raw_text',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
