# Generated by Django 5.2.8 on 2026-02-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_posting_raw_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
