# Generated by Django 5.2.8 on 2026-02-12 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_alter_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='job.job'),
        ),
    ]
