# Generated by Django 5.2.8 on 2026-02-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_alter_posting_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('IG', 'Ignored'), ('NA', 'Not Applied'), ('AF', 'Applied'), ('CR', 'Call Received'), ('IS', 'Interview Scheduled'), ('RP', 'Response Pending'), ('NE', 'Negotiating'), ('RE', 'Rejected'), ('OR', 'Offer Received'), ('AC', 'Application Closed')], default='NA', max_length=16),
        ),
    ]
