# Generated by Django 5.2.8 on 2026-02-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_interaction',
            field=models.DateField(null=True),
        ),
    ]
