# Generated by Django 5.2.8 on 2026-02-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_alter_job_last_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='platform_job_id',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        )
    ]
