# Generated by Django 5.2.8 on 2026-02-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_posting_platform_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_id',
        ),
    ]
