# Generated by Django 5.2.8 on 2026-02-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_remove_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='platform',
            field=models.CharField(choices=[('LI', 'linkedIn'), ('NI', 'naukri'), ('RAW', 'raw_data')], max_length=16, unique=True),
        ),
    ]
