# Generated by Django 5.2.8 on 2026-03-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_alter_session_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobraw',
            name='platform',
            field=models.CharField(choices=[('LI', 'linkedIn'), ('NI', 'naukri'), ('RAW', 'raw_data')], default='LI', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='tech_stack_all',
            field=models.CharField(max_length=512),
        ),
    ]
