# Generated by Django 5.2.8 on 2026-03-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_jobraw_platform_alter_job_tech_stack_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='platform',
            field=models.CharField(choices=[('LI', 'linkedIn'), ('NI', 'naukri'), ('RAW', 'raw_data')], default='LI', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='ratings',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
