# Generated by Django 5.2.8 on 2026-03-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_job_platform_job_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='first_response_date',
            field=models.DateField(null=True),
        ),
    ]
