# Generated by Django 5.2.8 on 2026-03-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0026_job_first_response_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='role_category',
            field=models.CharField(blank=True, choices=[('backend', 'backend'), ('frontend', 'frontend'), ('fullstack', 'fullstack'), ('data_engineer', 'data_engineer'), ('data_science', 'data_science'), ('devops', 'devops'), ('mobile', 'mobile'), ('qa', 'qa')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='role_summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='role_title',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='seniority_level',
            field=models.CharField(blank=True, choices=[('intern', 'intern'), ('junior', 'junior'), ('mid', 'mid'), ('senior', 'senior'), ('lead', 'lead'), ('manager', 'manager'), ('director', 'director'), ('vp', 'vp'), ('cto', 'cto')], max_length=16, null=True),
        ),
    ]
