# Generated by Django 5.2.8 on 2026-03-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0027_job_role_category_job_role_summary_job_role_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tech_stack_all_new',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tech_stack_primary_new',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
