# Generated by Django 5.2.8 on 2026-03-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0028_job_tech_stack_all_new_job_tech_stack_primary_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='role_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
