# Generated by Django 5.2.8 on 2026-07-16 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0029_alter_job_role_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='platform',
            field=models.CharField(choices=[('LI', 'linkedIn'), ('NI', 'naukri'), ('M', 'manual'), ('RAW', 'raw_data')], max_length=16),
        ),
        migrations.AlterField(
            model_name='jobraw',
            name='platform',
            field=models.CharField(choices=[('LI', 'linkedIn'), ('NI', 'naukri'), ('M', 'manual'), ('RAW', 'raw_data')], max_length=16),
        ),
        migrations.AlterField(
            model_name='session',
            name='platform',
            field=models.CharField(choices=[('LI', 'linkedIn'), ('NI', 'naukri'), ('M', 'manual'), ('RAW', 'raw_data')], max_length=16, unique=True),
        ),
        migrations.CreateModel(
            name='StatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IG', 'Ignored'), ('NA', 'Not Applied'), ('AF', 'Applied'), ('CR', 'Call Received'), ('IS', 'Interview Scheduled'), ('RP', 'Response Pending'), ('NE', 'Negotiating'), ('RE', 'Rejected'), ('OR', 'Offer Received'), ('AC', 'Application Closed')], max_length=16)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='job.job')),
            ],
        ),
    ]
