# Generated by Django 5.2.8 on 2026-07-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0030_alter_job_platform_alter_jobraw_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='role_category',
            field=models.CharField(blank=True, choices=[('backend', 'backend'), ('frontend', 'frontend'), ('fullstack', 'fullstack'), ('data_engineer', 'data_engineer'), ('data_science', 'data_science'), ('devops', 'devops'), ('mobile', 'mobile'), ('qa', 'qa'), ('other', 'other')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='seniority_level',
            field=models.CharField(blank=True, choices=[('intern', 'intern'), ('junior', 'junior'), ('mid', 'mid'), ('senior', 'senior'), ('lead', 'lead'), ('manager', 'manager'), ('director', 'director'), ('vp', 'vp'), ('cto', 'cto'), ('other', 'other')], max_length=16, null=True),
        ),
    ]
