# Generated by Django 5.2.8 on 2026-08-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0031_alter_job_role_category_alter_job_seniority_level'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-last_interaction'], name='idx_job_last_interaction'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='idx_job_status'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['applied_on'], name='idx_job_applied_on'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['first_response_date'], name='idx_job_first_resp'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'applied_on'], name='idx_job_status_applied'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['platform'], name='idx_job_platform'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['experience_min', 'experience_max'], name='idx_job_experience'),
        ),
    ]
