# Generated by Django 5.2.8 on 2026-08-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0032_job_idx_job_last_interaction_job_idx_job_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-last_posted'], name='idx_job_last_posted'),
        ),
    ]
