# Generated by Django 5.2.8 on 2026-09-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0033_job_idx_job_last_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('IG', 'Ignored'), ('NA', 'Not Applied'), ('MA', 'Matched'), ('AF', 'Applied'), ('AS', 'Assessment / Take-Home'), ('CR', 'Call Received'), ('IS', 'Interview Scheduled'), ('RP', 'Response Pending'), ('NE', 'Negotiating'), ('RE', 'Rejected'), ('OR', 'Offer Received'), ('AC', 'Application Closed')], default='NA', max_length=16),
        ),
        migrations.AlterField(
            model_name='statusevent',
            name='status',
            field=models.CharField(choices=[('IG', 'Ignored'), ('NA', 'Not Applied'), ('MA', 'Matched'), ('AF', 'Applied'), ('AS', 'Assessment / Take-Home'), ('CR', 'Call Received'), ('IS', 'Interview Scheduled'), ('RP', 'Response Pending'), ('NE', 'Negotiating'), ('RE', 'Rejected'), ('OR', 'Offer Received'), ('AC', 'Application Closed')], max_length=16),
        ),
    ]
