# Generated by Django 5.2.8 on 2026-09-11 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0034_alter_job_status_alter_statusevent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=128, unique=True)),
                ('processed', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('added_to_job', models.BooleanField(default=False)),
                ('added_to_parser', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('mapped_to', models.CharField(blank=True, max_length=128, null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.job')),
            ],
        ),
    ]
