# Generated by Django 5.2.8 on 2026-09-22 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0035_unknowntech'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField()),
                ('decision', models.CharField(max_length=16)),
                ('reasoning', models.TextField()),
                ('role_relevance', models.CharField(blank=True, max_length=16, null=True)),
                ('candidate_level', models.CharField(blank=True, max_length=16, null=True)),
                ('job_level', models.CharField(blank=True, max_length=16, null=True)),
                ('salary_alignment', models.CharField(blank=True, max_length=16, null=True)),
                ('applicant_context', models.TextField()),
                ('job_context', models.TextField()),
                ('prompt', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobMatchCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=128)),
                ('job_requires', models.JSONField()),
                ('candidate_has', models.JSONField()),
                ('importance', models.CharField(max_length=16)),
                ('coverage', models.CharField(max_length=16)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_clusters', to='job.jobmatch')),
            ],
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='core_foundation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='core_for_match', to='job.jobmatchcluster'),
        ),
    ]
