# Generated by Django 5.2.8 on 2026-09-28 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0036_jobmatch_jobmatchcluster_jobmatch_core_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=32, unique=True)),
                ('username', models.CharField(blank=True, max_length=128)),
                ('login_url', models.URLField(blank=True)),
                ('is_healthy', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(null=True)),
                ('daily_count', models.IntegerField(default=0)),
                ('daily_limit', models.IntegerField(default=50)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('IG', 'Ignored'), ('NA', 'Not Applied'), ('MA', 'Matched'), ('PR', 'Pending Review'), ('AF', 'Applied'), ('AS', 'Assessment / Take-Home'), ('CR', 'Call Received'), ('IS', 'Interview Scheduled'), ('RP', 'Response Pending'), ('NE', 'Negotiating'), ('RE', 'Rejected'), ('OR', 'Offer Received'), ('AC', 'Application Closed')], default='NA', max_length=16),
        ),
        migrations.AlterField(
            model_name='statusevent',
            name='status',
            field=models.CharField(choices=[('IG', 'Ignored'), ('NA', 'Not Applied'), ('MA', 'Matched'), ('PR', 'Pending Review'), ('AF', 'Applied'), ('AS', 'Assessment / Take-Home'), ('CR', 'Call Received'), ('IS', 'Interview Scheduled'), ('RP', 'Response Pending'), ('NE', 'Negotiating'), ('RE', 'Rejected'), ('OR', 'Offer Received'), ('AC', 'Application Closed')], max_length=16),
        ),
        migrations.CreateModel(
            name='ActionSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(db_index=True, max_length=256, unique=True)),
                ('snippet_type', models.CharField(max_length=16)),
                ('platform', models.CharField(blank=True, max_length=32)),
                ('field_label', models.CharField(blank=True, max_length=128)),
                ('page_url_pattern', models.CharField(blank=True, max_length=256)),
                ('action', models.JSONField()),
                ('verify', models.JSONField()),
                ('total_uses', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('fail_count', models.IntegerField(default=0)),
                ('consecutive_fails', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(null=True)),
                ('llm_reasoning', models.TextField(blank=True, null=True)),
                ('dom_context', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['platform', 'field_label'], name='idx_snippet_platform_label'), models.Index(fields=['snippet_type'], name='idx_snippet_type')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('IN_PROGRESS', 'In Progress'), ('PENDING_REVIEW', 'Pending Review'), ('REVIEW_APPROVED', 'Review Approved'), ('SUBMITTED', 'Submitted'), ('SUBMIT_FAILED', 'Submit Failed'), ('ESCALATED', 'Escalated'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=24)),
                ('apply_type', models.CharField(blank=True, max_length=24, null=True)),
                ('checkpoint_id', models.CharField(blank=True, max_length=128, null=True)),
                ('had_fresh_decisions', models.BooleanField(default=False)),
                ('auto_submit_eligible', models.BooleanField(default=False)),
                ('skip_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('escalation_reason', models.TextField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_runs', to='job.job')),
            ],
        ),
        migrations.CreateModel(
            name='StepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('page_url', models.URLField(max_length=512)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='apply_screenshots/')),
                ('dom_signature', models.CharField(max_length=128)),
                ('source', models.CharField(max_length=16)),
                ('action_type', models.CharField(max_length=24)),
                ('action_detail', models.JSONField()),
                ('success', models.BooleanField(default=True)),
                ('post_action_url', models.URLField(blank=True, max_length=512, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='job.applicationrun')),
            ],
            options={
                'ordering': ['run', 'step_number'],
            },
        ),
    ]
